project:
  type: book

lang: ru

book:
  title: "База знаний СНК кафедры фармакологии Российского университета медицины"
  author: "Сергей Царегородцев"
  date: today
  search: 
    location: sidebar
    type: textbox
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters: 
        - search.qmd
        - evaluation.qmd
        - review.qmd
        - bibliography.qmd
        - competitions.qmd
        - resources.qmd
    - telegram.qmd
    - media_example.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    download-buttons: true
  pdf:
    documentclass: book
    papersize: a4
    geometry:
      - top=2.5cm
      - bottom=2.5cm
      - left=2.5cm
      - right=2.5cm
    fontsize: 12pt
    linestretch: 1.5
    toc: true
    number-sections: true
    colorlinks: true
    linkcolor: blue
    urlcolor: blue
    citecolor: blue

prefer-html: true

editor: visual

callout-appearance: simple
callout-icon: false

  
author:
  - name:
      given: Сергей
      family: Царегородцев
      literal: С.В. Царегородцев
    orcid: 0000-0002-0254-0516
    email: sergiotsar@ya.ru

extensions:
  - quarto-ext/fontawesome
