---
title: "Разделы"
format: html
---

-   В главе "@sec-literature_search" описывается подготовка к поиску литературы, формулирование исследовательского вопроса, выбор баз данных и стратегий поиска с акцентом на доказательность.

-   В главе "@sec-evaluation" подробно рассматриваются критерии отбора научных публикаций, наукометрические показатели, квартили журналов и способы выявления потенциальных проблем и несоответствий в публикации (например, конфликт интересов).

-   В главе "@sec-literature_review" описывается, как подготовить качественный обзор литературы, избегая простого перечисления источников, и приводится структура научной статьи по модели IMRAD.

-   В главе "@sec-bibliography" даются рекомендации по использованию библиографических менеджеров и приведены ссылки на полезные инструкции и плагины. Рассматриваются требования ГОСТ для оформления списка литературы.

-   В главе "@sec-competitions" описываются актуальные конкурсы университетов и студенческого научного общества РосУниМеда, включая сроки подачи работ, контактную информацию и полезные ссылки.

-   В главе "@sec-resources" собраны ссылки на сайты, курсы, сервисы визуализации данных и другие материалы, которые могут пригодиться при подготовке научной работы.

Перед тем как приступить к использованию ресурса, рекомендуется посмотреть презентацию и видеоурок, которые приведены в разделе «Оформление библиографии и Zotero». Они помогут быстрее ориентироваться в инструментах и требованиях к оформлению.

::: callout-caution
## ️Все рекомендации носят информационный характер. Перед началом работы с конкретным журналом или конференцией обязательно ознакомьтесь с официальными требованиями к оформлению и сроками подачи материалов.
:::